import React, { useEffect, useState } from "react";
import { DEFAULT_EVOLUTION_INSTANCE, DEFAULT_EVOLUTION_KEY, DEFAULT_EVOLUTION_URL, getConfig, mascaraTelefone, numeroBR, setConfig } from "../supabaseClient";

function getQr(data){return data?.base64 || data?.qrcode?.base64 || data?.qrcode || data?.qr || data?.code || "";}

export default function Configuracoes({ session }) {
  const isAdmin=session?.perfil==="Administrador"||session?.perfil==="admin"||session?.usuario==="admin"||session?.usuario==="olitech";
  const [whatsappEmpresa,setWhatsappEmpresa]=useState("");
  const [evolutionUrl,setEvolutionUrl]=useState(DEFAULT_EVOLUTION_URL);
  const [evolutionKey,setEvolutionKey]=useState(DEFAULT_EVOLUTION_KEY);
  const [evolutionInstance,setEvolutionInstance]=useState(DEFAULT_EVOLUTION_INSTANCE);
  const [status,setStatus]=useState(null),[qrCode,setQrCode]=useState(""),[mostrarAvancado,setMostrarAvancado]=useState(false);
  const [testeNumero,setTesteNumero]=useState(""),[testeMensagem,setTesteMensagem]=useState("Teste WhatsApp Loja ✅");

  useEffect(()=>{async function c(){setWhatsappEmpresa(await getConfig("whatsapp_empresa",""));setEvolutionUrl(await getConfig("evolution_url",DEFAULT_EVOLUTION_URL));setEvolutionKey(await getConfig("evolution_key",DEFAULT_EVOLUTION_KEY));setEvolutionInstance(await getConfig("evolution_instance",DEFAULT_EVOLUTION_INSTANCE));} c();},[]);
  async function salvar(){if(!isAdmin)return alert("Apenas administrador pode alterar configurações."); await setConfig("whatsapp_empresa",numeroBR(whatsappEmpresa)); await setConfig("evolution_url",evolutionUrl); await setConfig("evolution_key",evolutionKey); await setConfig("evolution_instance",evolutionInstance); alert("Configurações salvas.");}
  async function consultarStatus(){try{const r=await fetch(`${evolutionUrl}/instance/connectionState/${evolutionInstance}`,{headers:{apikey:evolutionKey}}); setStatus(await r.json().catch(()=>({})));}catch(err){setStatus({erro:err.message});}}
  async function gerarQrCode(){if(!isAdmin)return alert("Apenas administrador pode gerar QR Code."); setQrCode(""); try{let r=await fetch(`${evolutionUrl}/instance/connect/${evolutionInstance}`,{method:"GET",headers:{apikey:evolutionKey}}); let data=await r.json().catch(()=>({})); if(!r.ok){r=await fetch(`${evolutionUrl}/instance/connect/${evolutionInstance}`,{method:"POST",headers:{"Content-Type":"application/json",apikey:evolutionKey},body:JSON.stringify({})}); data=await r.json().catch(()=>({}));} const qr=getQr(data); if(!qr){setStatus(data);alert("QR Code não retornou. Se já estiver conectado, clique em Trocar número/Desconectar primeiro.");return;} setQrCode(qr); consultarStatus();}catch(err){alert("Erro ao gerar QR Code: "+err.message);}}
  async function desconectar(){if(!isAdmin)return alert("Apenas administrador pode desconectar."); if(!confirm("Desconectar o WhatsApp atual para conectar outro número?"))return; try{await fetch(`${evolutionUrl}/instance/logout/${evolutionInstance}`,{method:"DELETE",headers:{apikey:evolutionKey}}); setQrCode(""); consultarStatus(); alert("Desconectado. Agora clique em Gerar QR Code.");}catch(err){alert("Erro ao desconectar: "+err.message);}}
  async function testarEnvio(){try{const number=numeroBR(testeNumero||whatsappEmpresa); if(!number)return alert("Informe um número para teste."); const r=await fetch(`${evolutionUrl}/message/sendText/${evolutionInstance}`,{method:"POST",headers:{"Content-Type":"application/json",apikey:evolutionKey},body:JSON.stringify({number,text:testeMensagem,delay:1200})}); const data=await r.json().catch(()=>({})); if(!r.ok||data?.error)return alert("Erro ao enviar: "+JSON.stringify(data)); alert("Mensagem enviada.");}catch(err){alert("Erro ao testar envio: "+err.message);}}
  const estado=status?.instance?.state||status?.state||status?.status||"não consultado"; const conectado=String(estado).toLowerCase().includes("open")||String(estado).toLowerCase().includes("connected");
  return <div className="card"><h2>⚙️ WhatsApp da Loja</h2><div className="status-whatsapp"><b>Status: <span className={conectado?"ok":"bad"}>{String(estado)}</span></b><button className="btn secondary" onClick={consultarStatus}>Atualizar status</button></div><label className="form-group">Número WhatsApp da loja<input placeholder="(16) 99607-6918" value={mascaraTelefone(whatsappEmpresa)} onChange={e=>setWhatsappEmpresa(e.target.value)}/></label><div className="actions"><button className="btn" onClick={salvar} disabled={!isAdmin}>Salvar número</button><button className="btn secondary" onClick={gerarQrCode} disabled={!isAdmin}>Conectar celular / Gerar QR Code</button><button className="btn danger" onClick={desconectar} disabled={!isAdmin}>Trocar número / Desconectar</button></div>{qrCode&&<div className="qr-box"><h3>Escaneie no WhatsApp</h3><p>WhatsApp → Aparelhos conectados → Conectar aparelho</p>{String(qrCode).startsWith("data:image")||String(qrCode).startsWith("http")?<img src={qrCode} alt="QR Code WhatsApp"/>:String(qrCode).length>100?<img src={`data:image/png;base64,${qrCode}`} alt="QR Code WhatsApp"/>:<div className="pair-code">{qrCode}</div>}</div>}<hr/><h2>Teste de envio</h2><div className="form-grid"><label className="form-group">Número para teste<input placeholder="Vazio = número da loja" value={mascaraTelefone(testeNumero)} onChange={e=>setTesteNumero(e.target.value)}/></label><label className="form-group">Mensagem<input value={testeMensagem} onChange={e=>setTesteMensagem(e.target.value)}/></label></div><button className="btn" onClick={testarEnvio}>Enviar teste</button><hr/><button className="btn secondary" onClick={()=>setMostrarAvancado(!mostrarAvancado)}>{mostrarAvancado?"Ocultar avançado":"Avançado"}</button>{mostrarAvancado&&<div className="advanced-box"><label className="form-group">Evolution URL<input value={evolutionUrl} onChange={e=>setEvolutionUrl(e.target.value)}/></label><label className="form-group">API Key<input value={evolutionKey} onChange={e=>setEvolutionKey(e.target.value)}/></label><label className="form-group">Instance<input value={evolutionInstance} onChange={e=>setEvolutionInstance(e.target.value)}/></label><button className="btn" onClick={salvar} disabled={!isAdmin}>Salvar avançado</button></div>}</div>;
}
