import React, { useEffect, useState } from "react";
import { limpar, supabase } from "../supabaseClient";

export default function Contatos() {
  const [clientes,setClientes]=useState([]),[contatos,setContatos]=useState([]),[sel,setSel]=useState([]);
  async function carregar(){const {data,error}=await supabase.from("clientes").select("*").order("nome"); if(error)return alert(error.message); setClientes(data||[]);}
  useEffect(()=>{carregar();},[]);
  function parseVCF(texto){return texto.split("END:VCARD").map(card=>{const nome=(card.match(/FN:(.*)/i)||[])[1]||(card.match(/N:(.*)/i)||[])[1]||""; const tels=[...card.matchAll(/TEL[^:]*:(.*)/gi)].map(m=>limpar(m[1])).filter(Boolean); const tel=tels[0]||""; return {nome:nome.replaceAll(";"," ").trim(),telefone:tel,whatsapp:tel,origem:"vcf",ativo:true};}).filter(c=>c.nome&&c.telefone);}
  function parseCSV(texto){return texto.split(/\r?\n/).map(l=>l.split(/[;,]/)).filter(c=>c[0]&&c[1]).map(c=>({nome:c[0].trim(),telefone:limpar(c[1]),whatsapp:limpar(c[1]),origem:"csv",ativo:true}));}
  function arquivo(e){const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=(ev)=>{const texto=String(ev.target.result||""); const lista=f.name.toLowerCase().endsWith(".vcf")?parseVCF(texto):parseCSV(texto); setContatos(lista);setSel(lista.map((_,i)=>i)); if(!lista.length)alert("Nenhum contato encontrado. Use .vcf ou CSV nome;telefone.");}; r.readAsText(f);}
  async function importar(){const lista=contatos.filter((_,i)=>sel.includes(i)); if(!lista.length)return alert("Selecione contatos."); for(const c of lista){const existe=clientes.some(x=>limpar(x.whatsapp||x.telefone)===limpar(c.whatsapp||c.telefone)); if(!existe) await supabase.from("clientes").insert(c);} alert("Contatos importados.");setContatos([]);setSel([]);carregar();}
  function exportar(){const csv=["nome,telefone,whatsapp",...clientes.map(c=>[c.nome||"",c.telefone||"",c.whatsapp||""].join(","))].join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); a.download="clientes.csv"; a.click();}
  return <div className="card"><h2>📲 Importar / Exportar Contatos</h2><div className="import-box"><p>Android: exporte contatos como <b>.vcf</b>. iPhone: exporte vCard pelo iCloud.</p><label className="btn">Importar contatos do celular<input type="file" accept=".vcf,.csv,text/vcard,text/csv" onChange={arquivo} style={{display:"none"}}/></label><button className="btn secondary" onClick={exportar}>Exportar clientes CSV</button></div>{contatos.length>0&&<><hr/><h3>Escolha os contatos para importar</h3><div className="actions"><button className="btn secondary" onClick={()=>setSel(contatos.map((_,i)=>i))}>Selecionar todos</button><button className="btn secondary" onClick={()=>setSel([])}>Limpar</button><button className="btn" onClick={importar}>Importar selecionados</button></div><div className="cards-list">{contatos.map((c,i)=><label className="permission-item" key={i}><input type="checkbox" checked={sel.includes(i)} onChange={()=>setSel(sel.includes(i)?sel.filter(x=>x!==i):[...sel,i])}/><span><b>{c.nome}</b><br/>{c.telefone}</span></label>)}</div></>}<hr/><h3>Clientes cadastrados</h3><div className="cards-list">{clientes.map(c=><div key={c.id} className="mini-card"><b>{c.nome}</b><p>{c.whatsapp||c.telefone}</p><button className="btn secondary" onClick={()=>window.open(`https://wa.me/55${limpar(c.whatsapp||c.telefone)}`,"_blank")}>WhatsApp</button></div>)}</div></div>;
}
