import React, { useEffect, useMemo, useState } from "react";
import { moeda, dataBR, supabase } from "../supabaseClient";
import SearchSelect from "./SearchSelect";

export default function Relatorios() {
  const [agendamentos,setAgendamentos]=useState([]),[atendentes,setAtendentes]=useState([]),[clientes,setClientes]=useState([]),[servicos,setServicos]=useState([]);
  const [f,setF]=useState({inicio:"",fim:"",cliente:"",atendente:"",servico:"",status:""});
  async function carregar(){
    const ag=await supabase.from("agendamentos").select("*").order("data_agendamento",{ascending:false});
    const at=await supabase.from("atendentes").select("*").order("nome");
    const cl=await supabase.from("clientes").select("*").order("nome");
    const se=await supabase.from("servicos").select("*").order("nome");
    setAgendamentos(ag.data||[]);setAtendentes(at.data||[]);setClientes(cl.data||[]);setServicos(se.data||[]);
  }
  useEffect(()=>{carregar();},[]);
  const lista=useMemo(()=>agendamentos.filter(a=>!(f.inicio&&String(a.data_agendamento||"")<f.inicio)&&!(f.fim&&String(a.data_agendamento||"")>f.fim)&&!(f.cliente&&!String(a.cliente_nome||"").toLowerCase().includes(f.cliente.toLowerCase()))&&!(f.atendente&&!String(a.atendente_nome||"").toLowerCase().includes(f.atendente.toLowerCase()))&&!(f.servico&&!String(a.servico||"").toLowerCase().includes(f.servico.toLowerCase()))&&!(f.status&&a.status!==f.status)),[agendamentos,f]);
  const resumo=useMemo(()=>{const mapa={}; for(const a of lista){const nome=a.atendente_nome||"Sem atendente"; const at=atendentes.find(x=>x.nome===nome); const perc=Number(at?.comissao_servico_percentual||0)||Number(at?.comissao_percentual||0); const total=Number(a.total||0); if(!mapa[nome])mapa[nome]={atendente:nome,qtd:0,total:0,recebido:0,comissao:0}; mapa[nome].qtd++; mapa[nome].total+=total; mapa[nome].recebido+=Number(a.valor_sinal||0)+Number(a.valor_recebido||0); mapa[nome].comissao+=total*(perc/100);} return Object.values(mapa);},[lista,atendentes]);
  const total=lista.reduce((s,a)=>s+Number(a.total||0),0), recebido=lista.reduce((s,a)=>s+Number(a.valor_sinal||0)+Number(a.valor_recebido||0),0), saldo=lista.reduce((s,a)=>s+Number(a.saldo||0),0), comissao=resumo.reduce((s,a)=>s+a.comissao,0);
  return <div className="card"><h2>📈 Relatórios</h2><div className="form-grid"><label className="form-group">Data inicial<input type="date" value={f.inicio} onChange={e=>setF({...f,inicio:e.target.value})}/></label><label className="form-group">Data final<input type="date" value={f.fim} onChange={e=>setF({...f,fim:e.target.value})}/></label><SearchSelect label="Cliente" items={clientes} value={f.cliente} getValue={(x)=>x.nome} onChange={(c)=>setF({...f,cliente:c?.nome||""})}/><SearchSelect label="Atendente" items={atendentes} value={f.atendente} getValue={(x)=>x.nome} onChange={(a)=>setF({...f,atendente:a?.nome||""})}/><SearchSelect label="Serviço" items={servicos} value={f.servico} getValue={(x)=>x.nome} onChange={(s)=>setF({...f,servico:s?.nome||""})}/><label className="form-group">Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="">Todos</option><option value="pendente">Pendente</option><option value="confirmado">Confirmado</option><option value="finalizado">Finalizado</option><option value="cancelado">Cancelado</option></select></label></div><div className="actions"><button className="btn secondary" onClick={()=>setF({inicio:"",fim:"",cliente:"",atendente:"",servico:"",status:""})}>Limpar filtros</button></div><hr/><div className="grid-dashboard"><div className="dashboard-card"><h2>Total</h2><h1>R$ {moeda(total)}</h1></div><div className="dashboard-card"><h2>Recebido</h2><h1>R$ {moeda(recebido)}</h1></div><div className="dashboard-card"><h2>Saldo</h2><h1>R$ {moeda(saldo)}</h1></div><div className="dashboard-card"><h2>Comissões</h2><h1>R$ {moeda(comissao)}</h1></div></div><hr/><h2>Comissão por atendente</h2><div className="table-wrap"><table><thead><tr><th>Atendente</th><th>Qtd.</th><th>Total</th><th>Recebido</th><th>Comissão</th></tr></thead><tbody>{resumo.map(r=><tr key={r.atendente}><td data-label="Atendente">{r.atendente}</td><td data-label="Qtd.">{r.qtd}</td><td data-label="Total">R$ {moeda(r.total)}</td><td data-label="Recebido">R$ {moeda(r.recebido)}</td><td data-label="Comissão">R$ {moeda(r.comissao)}</td></tr>)}</tbody></table></div><hr/><h2>Agendamentos filtrados</h2><div className="cards-list">{lista.map(a=><div key={a.id} className="mini-card"><b>{a.cliente_nome}</b><br/>Atendente: {a.atendente_nome}<br/>Serviço: {a.servico}<br/>Data: {dataBR(a.data_agendamento)} {a.hora_agendamento}<br/>Total: R$ {moeda(a.total)}<br/>Recebido: R$ {moeda(Number(a.valor_sinal||0)+Number(a.valor_recebido||0))}<br/>Saldo: R$ {moeda(a.saldo)}<br/>Status: {a.status}</div>)}</div></div>;
}
